In [1]:
import pandas as pd
from urllib.request import urlopen
# from geopy.geocoders import Nominatim
import numpy as np
import os
import csv
import datetime as dt


# import json
import json
# store the URL in url as 
# parameter for urlopen

## API URL  - using quakes MMI "2" - "7"
url2 = "https://api.geonet.org.nz/quake?MMI=2"
url3 = "https://api.geonet.org.nz/quake?MMI=3"
url4 = "https://api.geonet.org.nz/quake?MMI=4"
url5 = "https://api.geonet.org.nz/quake?MMI=5"
url6 = "https://api.geonet.org.nz/quake?MMI=6"
url7 = "https://api.geonet.org.nz/quake?MMI=7"

In [2]:
## Create DF for each API request at varying levels of MMI 
# ---------------------------
# MMI = 2
# ---------------------------
# store the response of URL
response2 = urlopen(url2)
  
# storing the JSON response 
# from url in data
data_json2 = json.loads(response2.read())

MMI2_df = pd.json_normalize(data_json2["features"])
# MMI2_df.head()

# ---------------------------
# MMI = 3
# ---------------------------
# store the response of URL
response3 = urlopen(url3)
  
# storing the JSON response 
# from url in data
data_json3 = json.loads(response3.read())

MMI3_df = pd.json_normalize(data_json3["features"])
# MMI2_df.head()

# ---------------------------
# MMI = 4
# ---------------------------
# store the response of URL
response4 = urlopen(url4)
  
# storing the JSON response 
# from url in data
data_json4 = json.loads(response4.read())

MMI4_df = pd.json_normalize(data_json4["features"])
# MMI4_df.head()


# ---------------------------
# MMI = 5
# ---------------------------
# store the response of URL
response5 = urlopen(url5)
  
# storing the JSON response 
# from url in data
data_json5 = json.loads(response5.read())

MMI5_df = pd.json_normalize(data_json5["features"])
# MMI5_df.head()

# ---------------------------
# MMI = 6
# ---------------------------
# store the response of URL
response6 = urlopen(url6)
  
# storing the JSON response 
# from url in data
data_json6 = json.loads(response6.read())

MMI6_df = pd.json_normalize(data_json6["features"])
# MMI6_df.head()

# ---------------------------
# MMI = 7
# ---------------------------
# store the response of URL
response7 = urlopen(url7)
  
# storing the JSON response 
# from url in data
data_json7 = json.loads(response7.read())

MMI7_df = pd.json_normalize(data_json7["features"])
# MMI7_df.head()

In [3]:
# Union raw all dataframes via concat
# Put into list then concat.

MMI_raw_df_list = [MMI2_df,MMI3_df,MMI4_df,MMI5_df,MMI6_df,MMI7_df]
MMI_union_df = pd.concat(MMI_raw_df_list)
# union_raw_df.count()

MMI_union_df.head()

,type,geometry.type,geometry.coordinates,properties.publicID,properties.time,properties.depth,properties.magnitude,properties.mmi,properties.locality,properties.quality
0,Feature,Point,"[179.2304688, -32.44289398]",2023p460436,2023-06-20T08:39:16.406Z,500.000000,2.923297,-1,580 km north-east of Whangarei,best
1,Feature,Point,"[175.7494354, -38.89125443]",2023p460409,2023-06-20T08:26:02.708Z,5.000000,1.169254,-1,10 km north of Turangi,preliminary
2,Feature,Point,"[174.2625122, -41.60854721]",2023p460347,2023-06-20T07:53:24.069Z,9.987767,1.296283,-1,15 km north-east of Seddon,best
3,Feature,Point,"[176.3666637, -39.64257937]",2023p460323,2023-06-20T07:40:28.334Z,5.468750,1.820172,0,40 km west of Hastings,deleted
4,Feature,Point,"[178.8334961, -31.58815193]",2023p460319,2023-06-20T07:36:58.518Z,300.000000,3.611778,-1,620 km north-east of Whangarei,best

In [4]:
## Split geometry.coordinates into longitude and latitude

MMI_union_df = MMI_union_df.astype({'geometry.coordinates':'string'})
MMI_union_df

# Split the "geometry.coordinates" column into "longitude" and "latitude" columns
MMI_union_df['longitude'] = MMI_union_df['geometry.coordinates'].str.split(',').str[0].str.strip('[ ')
MMI_union_df['latitude'] = MMI_union_df['geometry.coordinates'].str.split(',').str[1].str.strip('] ')

# Convert the columns to the appropriate data type if needed
MMI_union_df['longitude'] = MMI_union_df['longitude'].astype(float)
MMI_union_df['latitude'] = MMI_union_df['latitude'].astype(float)

# DF below combines all API Requests however is still raw from JSON.
MMI_union_df.head()

,type,geometry.type,geometry.coordinates,properties.publicID,properties.time,properties.depth,properties.magnitude,properties.mmi,properties.locality,properties.quality,longitude,latitude
0,Feature,Point,"[179.2304688, -32.44289398]",2023p460436,2023-06-20T08:39:16.406Z,500.000000,2.923297,-1,580 km north-east of Whangarei,best,179.230469,-32.442894
1,Feature,Point,"[175.7494354, -38.89125443]",2023p460409,2023-06-20T08:26:02.708Z,5.000000,1.169254,-1,10 km north of Turangi,preliminary,175.749435,-38.891254
2,Feature,Point,"[174.2625122, -41.60854721]",2023p460347,2023-06-20T07:53:24.069Z,9.987767,1.296283,-1,15 km north-east of Seddon,best,174.262512,-41.608547
3,Feature,Point,"[176.3666637, -39.64257937]",2023p460323,2023-06-20T07:40:28.334Z,5.468750,1.820172,0,40 km west of Hastings,deleted,176.366664,-39.642579
4,Feature,Point,"[178.8334961, -31.58815193]",2023p460319,2023-06-20T07:36:58.518Z,300.000000,3.611778,-1,620 km north-east of Whangarei,best,178.833496,-31.588152

In [7]:
## Final Clean and convert
## stage to additional clean, cut , convert and rename columns
## Check Index
# MMI_union_df.columns.get_loc("properties.publicID")

# Rename Columns
quake_mapping = {MMI_union_df.columns[3]:'publicID',MMI_union_df.columns[4]:'time',MMI_union_df.columns[5]:'depth',MMI_union_df.columns[6]:'magnitude',MMI_union_df.columns[7]:'mmi',MMI_union_df.columns[8]:'locality'}
MMI_new_column_df = MMI_union_df.rename(columns =quake_mapping)

#Create date column 
MMI_new_column_df['date'] =pd.to_datetime(MMI_new_column_df['time']).dt.strftime('%Y-%m-%d')

# strip back to columns needed.
MMI_new_clean_df = MMI_new_column_df[["publicID","date","mmi","magnitude","locality","longitude","latitude","time","depth"]]


# Convert into final data frame quake_mmi_df
quake_mmi_df = pd.DataFrame(MMI_new_clean_df)
quake_mmi_df.reset_index
quake_mmi_df = quake_mmi_df.drop_duplicates(keep='first')
quake_mmi_df.head()
quake_mmi_df.dtypes

publicID      object
date          object
mmi            int64
magnitude    float64
locality      object
longitude    float64
latitude     float64
time          object
depth        float64
dtype: object

In [6]:
# ## export to CSV without index
# quake_mmi_df.to_csv('quake_mmi_data.csv', encoding='utf-8',index=False)